### ISSUE TITLE
The newer version doesn't handle strings with single quotes

### ISSUE THREAD

**Issue by l1h2** [google/arb-editor#74] opened 2024-10-13 18:15 UTC
After the update all strings with single quotes (Ie.: can't) are showing an error:

Error: Unbalanced escape quotes. To escape a single quote ', prefix it with another single quote.(mismatched_brackets)

**Comment by mosuem** [comment] 2024-10-14 12:13
Thanks for filing this! Closing as duplicate of #72.

**Closed by mosuem** 2024-10-14 12:13 UTC
Labels: bug
